// apps/react-docs/demos/api/hooks/use-field-schema.tsx
import { createForm } from '@silver-formily/core'
import {
  createSchemaField,
  FormProvider,
  useFieldSchema,
} from '@silver-formily/react'

const form = createForm({ validateFirst: true })

// useFieldSchema 只能在 SchemaField 或 RecursionField 子树内使用
function Custom() {
  const schema = useFieldSchema()
  return (
    <div style={{ whiteSpace: 'pre' }}>
      {JSON.stringify(schema?.toJSON(), null, 4)}
    </div>
  )
}

const SchemaField = createSchemaField({
  components: {
    Custom,
  },
})

export default function Demo() {
  return (
    <FormProvider form={form}>
      <SchemaField>
        <SchemaField.Object
          name="custom"
          x-component="Custom"
          x-component-props={{
            schema: {
              type: 'object',
              properties: {
                input: {
                  'type': 'string',
                  'x-component': 'Custom',
                },
              },
            },
          }}
        />
      </SchemaField>
    </FormProvider>
  )
}

// apps/vue-docs/demos/api/hooks/use-field-schema.vue
<script setup lang="ts">
import { createForm } from '@silver-formily/core'
import { createSchemaField, FormProvider, useFieldSchema } from '@silver-formily/vue'
import { defineComponent, h } from 'vue'

const Custom = defineComponent({
  setup() {
    const schemaRef = useFieldSchema()
    return () => {
      const schema = schemaRef.value
      return h(
        'div',
        {
          style: { whiteSpace: 'pre' },
        },
        [JSON.stringify(schema.toJSON(), null, 4)],
      )
    }
  },
})

const { SchemaField, SchemaObjectField } = createSchemaField({
  components: {
    Custom,
  },
})
const form = createForm({ validateFirst: true })
</script>

<template>
  <FormProvider :form="form">
    <SchemaField>
      <SchemaObjectField
        name="custom"
        x-component="Custom"
        :x-component-props="{
          schema: {
            type: 'object',
            properties: {
              input: {
                'type': 'string',
                'x-component': 'Custom',
              },
            },
          },
        }"
      />
    </SchemaField>
  </FormProvider>
</template>
