// apps/vue-docs/demos/api/components/array-field.vue
<script setup lang="ts">
import { createForm } from '@silver-formily/core'
import { ArrayField, Field, FormProvider } from '@silver-formily/vue'
import { ElButton, ElInput, ElSpace } from 'element-plus'

const form = createForm()
</script>

<template>
  <FormProvider :form="form">
    <ArrayField name="array">
      <template #default="{ field }">
        <div
          v-for="(item, index) in field.value || []"
          :key="`${item.id}-${index}`"
          :style="{ marginBottom: '10px' }"
        >
          <ElSpace>
            <Field :name="`${index}.value`" :component="[ElInput]" />
            <ElButton
              @click="
                () => {
                  field.remove(index)
                }
              "
            >
              Remove
            </ElButton>
            <ElButton
              @click="
                () => {
                  field.moveUp(index)
                }
              "
            >
              Move Up
            </ElButton>
            <ElButton
              @click="
                () => {
                  field.moveDown(index)
                }
              "
            >
              Move Down
            </ElButton>
          </ElSpace>
        </div>
        <ElButton @click="() => field.push({ id: Date.now(), value: '' })">
          Add
        </ElButton>
      </template>
    </ArrayField>
  </FormProvider>
</template>

// apps/react-docs/demos/api/components/array-field.tsx
import { createForm } from '@silver-formily/core'
import { ArrayField, Field, FormProvider } from '@silver-formily/react'
import { Button, Input, Space } from 'antd'

const form = createForm()

export default function Demo() {
  return (
    <FormProvider form={form}>
      <ArrayField name="array">
        {field => (
          <div>
            {(field.value || []).map((item, index) => (
              <div
                key={`${item.id}-${index}`}
                style={{ marginBottom: 10 }}
              >
                <Space>
                  <Field name={`${index}.value`} component={[Input]} />
                  <Button onClick={() => field.remove(index)}>
                    Remove
                  </Button>
                  <Button onClick={() => field.moveUp(index)}>
                    Move Up
                  </Button>
                  <Button onClick={() => field.moveDown(index)}>
                    Move Down
                  </Button>
                </Space>
              </div>
            ))}
            <Button onClick={() => field.push({ id: Date.now(), value: '' })}>
              Add
            </Button>
          </div>
        )}
      </ArrayField>
    </FormProvider>
  )
}
