// apps/vue-docs/demos/api/components/field.vue
<script setup lang="ts">
import { createForm } from '@silver-formily/core'
import { Field, FormProvider } from '@silver-formily/vue'
import { ElInput } from 'element-plus'

const form = createForm({
  initialValues: {
    input: '初始值',
  },
})
</script>

<template>
  <FormProvider :form="form">
    <Field name="input" :component="[ElInput, { placeholder: '请输入' }]" />
  </FormProvider>
</template>

// apps/react-docs/demos/api/components/field.tsx
import { createForm } from '@silver-formily/core'
import { Field, FormProvider } from '@silver-formily/react'
import { Input } from 'antd'

const form = createForm({
  initialValues: {
    input: '初始值',
  },
})

export default function Demo() {
  return (
    <FormProvider form={form}>
      <Field name="input" component={[Input, { placeholder: '请输入' }]} />
    </FormProvider>
  )
}
