// apps/vue-docs/demos/api/components/form-consumer.vue
<script setup>
import { createForm } from '@silver-formily/core'
import { Field, FormConsumer, FormProvider } from '@silver-formily/vue'
import { ElInput } from 'element-plus'

const form = createForm()
</script>

<template>
  <FormProvider :form="form">
    <Field name="input" :component="[ElInput]" />
    <FormConsumer>
      <template #default="{ form: _form }">
        {{ _form.values.input }}
      </template>
    </FormConsumer>
  </FormProvider>
</template>

// apps/react-docs/demos/api/components/form-consumer.tsx
import { createForm } from '@silver-formily/core'
import { Field, FormConsumer, FormProvider } from '@silver-formily/react'
import { Input } from 'antd'

const form = createForm()

export default function Demo() {
  return (
    <FormProvider form={form}>
      <Field name="input" component={[Input]} />
      {/* children 是函数时，依赖的表单数据变化会触发回调重新执行 */}
      <FormConsumer>
        {form => form.values.input}
      </FormConsumer>
    </FormProvider>
  )
}
