// apps/vue-docs/demos/api/components/object-field.vue
<script setup lang="ts">
import { createForm } from '@silver-formily/core'
import { Field, FormProvider, ObjectField } from '@silver-formily/vue'
import { ElButton, ElInput, ElSpace } from 'element-plus'

const form = createForm()

function addPropertyToField(field: any) {
  const name = form.values.propertyName
  if (name && !form.existValuesIn(`object.${name}`)) {
    field.addProperty(name, '')
    form.deleteValuesIn('propertyName')
  }
}
</script>

<template>
  <FormProvider :form="form">
    <ObjectField name="object">
      <template #default="{ field }">
        <div
          v-for="key in Object.keys(field.value || {})"
          :key="key"
          :style="{ marginBottom: '10px' }"
        >
          <ElSpace>
            <Field :name="key" :component="[ElInput, { placeholder: key }]" />
            <ElButton @click="field.removeProperty(key)">
              Remove
            </ElButton>
          </ElSpace>
        </div>
        <ElSpace>
          <Field
            name="propertyName"
            base-path=""
            required
            :component="[ElInput, { placeholder: 'Property Name' }]"
          />
          <ElButton @click="addPropertyToField(field)">
            Add
          </ElButton>
        </ElSpace>
      </template>
    </ObjectField>
  </FormProvider>
</template>

// apps/react-docs/demos/api/components/object-field.tsx
import type { ObjectField as ObjectFieldType } from '@silver-formily/core'
import { createForm } from '@silver-formily/core'
import { Field, FormProvider, ObjectField } from '@silver-formily/react'
import { Button, Input, Space } from 'antd'

const form = createForm()

function addPropertyToField(field: ObjectFieldType) {
  const name = form.values.propertyName
  if (name && !form.existValuesIn(`object.${name}`)) {
    field.addProperty(name, '')
    form.deleteValuesIn('propertyName')
  }
}

export default function Demo() {
  return (
    <FormProvider form={form}>
      <ObjectField name="object">
        {field => (
          <div>
            {Object.keys(field.value || {}).map(key => (
              <div key={key} style={{ marginBottom: 10 }}>
                <Space>
                  <Field name={key} component={[Input, { placeholder: key }]} />
                  <Button onClick={() => field.removeProperty(key)}>
                    Remove
                  </Button>
                </Space>
              </div>
            ))}
            <Space>
              <Field
                name="propertyName"
                basePath=""
                required
                component={[Input, { placeholder: 'Property Name' }]}
              />
              <Button onClick={() => addPropertyToField(field)}>
                Add
              </Button>
            </Space>
          </div>
        )}
      </ObjectField>
    </FormProvider>
  )
}
