// apps/vue-docs/demos/api/components/schema-field.vue
<script setup>
import { createForm } from '@silver-formily/core'
import { createSchemaField, FormProvider } from '@silver-formily/vue'
import { ElInput } from 'element-plus'

const { SchemaField, SchemaStringField } = createSchemaField({
  components: {
    ElInput,
  },
})

const form = createForm()
</script>

<template>
  <FormProvider :form="form">
    <SchemaField>
      <SchemaStringField name="input" x-component="ElInput" />
    </SchemaField>
  </FormProvider>
</template>

// apps/react-docs/demos/api/components/schema-field.tsx
import { createForm } from '@silver-formily/core'
import { createSchemaField, FormProvider } from '@silver-formily/react'
import { Input } from 'antd'

const form = createForm()

// createSchemaField 返回的 SchemaField 上挂载了各 Markup 子组件
const SchemaField = createSchemaField({
  components: {
    Input,
  },
})

export default function Demo() {
  return (
    <FormProvider form={form}>
      <SchemaField>
        <SchemaField.String name="input" x-component="Input" />
      </SchemaField>
    </FormProvider>
  )
}
