// apps/vue-docs/demos/api/components/void-field.vue
<script setup lang="ts">
import { createForm } from '@silver-formily/core'
import { Field, FormConsumer, FormProvider, VoidField } from '@silver-formily/vue'
import { ElButton, ElInput, ElSpace } from 'element-plus'

const form = createForm()
</script>

<template>
  <FormProvider :form="form">
    <ElSpace>
      <VoidField name="layout">
        <Field name="input" :component="[ElInput]" />
      </VoidField>
      <FormConsumer>
        <template #default="{ form: _form }">
          <ElSpace>
            <ElButton
              @click="
                () => {
                  _form
                    .query('layout')
                    .take()
                    .setState((state) => {
                      state.visible = !state.visible
                    })
                }
              "
            >
              {{ form.query('layout').get('visible') ? 'Hide' : 'Show' }}
            </ElButton>
            <div>{{ JSON.stringify(form.values, null, 2) }}</div>
          </ElSpace>
        </template>
      </FormConsumer>
    </ElSpace>
  </FormProvider>
</template>

// apps/react-docs/demos/api/components/void-field.tsx
import { createForm } from '@silver-formily/core'
import { Field, FormConsumer, FormProvider, VoidField } from '@silver-formily/react'
import { Button, Input, Space } from 'antd'

const form = createForm()

export default function Demo() {
  return (
    <FormProvider form={form}>
      <Space>
        <VoidField name="layout">
          <Field name="input" component={[Input]} />
        </VoidField>
        <FormConsumer>
          {_form => (
            <Space>
              <Button
                onClick={() => {
                  _form
                    .query('layout')
                    .take()
                    ?.setState((state) => {
                      state.visible = !state.visible
                    })
                }}
              >
                {form.query('layout').get('visible') ? 'Hide' : 'Show'}
              </Button>
              <div style={{ whiteSpace: 'pre' }}>
                {JSON.stringify(form.values, null, 2)}
              </div>
            </Space>
          )}
        </FormConsumer>
      </Space>
    </FormProvider>
  )
}
