// apps/vue-docs/demos/api/hooks/use-parent-form.vue
<script setup lang="tsx">
import { createForm } from '@silver-formily/core'
import { observer } from '@silver-formily/reactive-vue'
import {
  FormProvider,
  ObjectField,
  useParentForm,
  VoidField,
} from '@silver-formily/vue'
import { ElText } from 'element-plus'
import { defineComponent } from 'vue'

const Custom = observer(
  defineComponent({
    name: 'Custom',
    setup() {
      const formRef = useParentForm()
      return () => (
        <p>
          <ElText>{formRef.value?.displayName}</ElText>
        </p>
      )
    },
  }),
)

const form = createForm()
</script>

<template>
  <FormProvider :form="form">
    <ObjectField name="object">
      <Custom />
    </ObjectField>
    <Custom />
    <VoidField name="void">
      <Custom />
    </VoidField>
  </FormProvider>
</template>

// apps/react-docs/demos/api/hooks/use-parent-form.tsx
import { createForm } from '@silver-formily/core'
import { FormProvider, ObjectField, observer, useParentForm, VoidField } from '@silver-formily/react'
import { Typography } from 'antd'

// useParentForm 返回最近的 Form 或 ObjectField，方便调用 submit / validate
const Custom = observer(() => {
  const parent = useParentForm()
  return (
    <p>
      <Typography.Text>
        {parent?.displayName}
      </Typography.Text>
    </p>
  )
})

const form = createForm()

export default function Demo() {
  return (
    <FormProvider form={form}>
      <ObjectField name="object">
        <Custom />
      </ObjectField>
      <Custom />
      <VoidField name="void">
        <Custom />
      </VoidField>
    </FormProvider>
  )
}
