// apps/vue-docs/demos/api/hooks/use-form.vue
<script setup lang="tsx">
import { createForm } from '@silver-formily/core'
import { observer } from '@silver-formily/reactive-vue'
import { Field, FormProvider, useForm } from '@silver-formily/vue'
import { ElInput, ElSpace } from 'element-plus'
import { defineComponent } from 'vue'

const Custom = observer(
  defineComponent({
    name: 'Custom',
    setup() {
      const formRef = useForm()
      return () => (
        <div>
          {formRef.value?.values.input}
        </div>
      )
    },
  }),
)

const form = createForm({ validateFirst: true })
</script>

<template>
  <FormProvider :form="form">
    <ElSpace>
      <Field name="input" :component="[ElInput]" />
      <Field name="custom" :component="[Custom]" />
    </ElSpace>
  </FormProvider>
</template>

// apps/react-docs/demos/api/hooks/use-form.tsx
import { createForm } from '@silver-formily/core'
import { Field, FormProvider, observer, useForm } from '@silver-formily/react'
import { Input, Space } from 'antd'

// 依赖 Form 状态的组件需要 observer 包裹才能响应更新
const Custom = observer(() => {
  const form = useForm()
  return (
    <div>
      {form.values.input}
    </div>
  )
})

const form = createForm({ validateFirst: true })

export default function Demo() {
  return (
    <FormProvider form={form}>
      <Space>
        <Field name="input" component={[Input]} />
        <Field name="custom" component={[Custom]} />
      </Space>
    </FormProvider>
  )
}
