// apps/vue-docs/demos/api/hooks/use-field.vue
<script setup lang="tsx">
import type { Field as FieldType } from '@formily/core'
import { createForm, setValidateLanguage } from '@formily/core'
import { observer } from '@silver-formily/reactive-vue'
import { Field, FormConsumer, FormProvider, useField } from '@silver-formily/vue'
import { ElButton, ElFormItem, ElInput } from 'element-plus'
import { defineComponent } from 'vue'

setValidateLanguage('en')

const FormItem = observer(
  defineComponent({
    setup(_props, { slots }) {
      const fieldRef = useField<FieldType>()
      return () => (
        <ElFormItem
          label={fieldRef.value?.title}
          required={fieldRef.value?.required}
          help={fieldRef.value?.selfErrors?.length ? fieldRef.value?.selfErrors : undefined}
          extra={fieldRef.value?.description}
          validateStatus={fieldRef.value?.validateStatus}
        >
          {slots?.default?.()}
        </ElFormItem>
      )
    },
  }),
)

const form = createForm({ validateFirst: true })

function log(values: string) {
  console.warn('Form Submitted:', values)
}
</script>

<template>
  <FormProvider :form="form">
    <Form layout="vertical">
      <Field
        name="name"
        title="Name"
        required
        :decorator="[FormItem]"
        :component="[ElInput, { placeholder: 'Please ElInput' }]"
      />
      <FormConsumer>
        <template #default="{ form: _form }">
          <div style="white-space: pre; margin-bottom: 16px">
            {{ JSON.stringify(_form.values, null, 2) }}
          </div>
          <ElButton
            type="primary"
            @click="
              () => {
                form.submit(log)
              }
            "
          >
            Submit
          </ElButton>
        </template>
      </FormConsumer>
    </Form>
  </FormProvider>
</template>

// apps/react-docs/demos/api/hooks/use-field.tsx
import type { Field as FieldType } from '@silver-formily/core'
import { createForm, setValidateLanguage } from '@silver-formily/core'
import { Field, FormConsumer, FormProvider, observer, useField } from '@silver-formily/react'
import { Button, Form, Input } from 'antd'

setValidateLanguage('en')

// 装饰器组件内通过 useField 读取字段实例，需要 observer 包裹才能响应字段变化
const FormItem = observer((props: { children?: React.ReactNode }) => {
  const field = useField<FieldType>()
  return (
    <Form.Item
      label={field?.title}
      required={field?.required}
      help={field?.selfErrors?.[0]}
      validateStatus={field?.validateStatus ?? undefined}
    >
      {props.children}
    </Form.Item>
  )
})

const form = createForm({ validateFirst: true })

function log(values: string) {
  console.warn('Form Submitted:', values)
}

export default function Demo() {
  return (
    <FormProvider form={form}>
      <Form layout="vertical">
        <Field
          name="name"
          title="Name"
          required
          decorator={[FormItem]}
          component={[Input, { placeholder: 'Please Input' }]}
        />
        <FormConsumer>
          {_form => (
            <>
              <div style={{ whiteSpace: 'pre', marginBottom: 16 }}>
                {JSON.stringify(_form.values, null, 2)}
              </div>
              <Button type="primary" onClick={() => form.submit(log)}>
                Submit
              </Button>
            </>
          )}
        </FormConsumer>
      </Form>
    </FormProvider>
  )
}
