// apps/reactive-react-docs/demos/observer.tsx
import { observable } from '@silver-formily/reactive'
import { observer } from '@silver-formily/reactive-react'
import './demoStyles.css'

const obs = observable({
  value: 'Hello world',
})

// observer 返回的组件在渲染时收集依赖，依赖变化只触发当前组件重渲染
const ObservedInput = observer(() => {
  return (
    <div>
      <input
        className="demoInput"
        value={obs.value}
        onChange={(event) => {
          obs.value = event.target.value
        }}
      />
      <div className="demoText">{obs.value}</div>
    </div>
  )
})

export default ObservedInput

// apps/reactive-vue-docs/demos/observer.vue
<script>
import { observable } from '@silver-formily/reactive'
import { observer } from '@silver-formily/reactive-vue'

export default observer({
  data() {
    // 能与 vue 的响应系统共存
    const obs = observable({
      value: 'Hello world',
    })
    return {
      obs,
    }
  },
})
</script>

<template>
  <div>
    <div>
      <input
        :style="{
          height: 28,
          padding: '0 8px',
          border: '2px solid #888',
          borderRadius: 3,
        }"
        :value="obs.value"
        @input="(e) => {
          obs.value = e.target.value
        }"
      >
    </div>
    <div>{{ obs.value }}</div>
  </div>
</template>
