// apps/react-docs/demos/api/shared/map-read-pretty.tsx
import { createForm, isVoidField, setValidateLanguage } from '@silver-formily/core'
import { connect, Field, FormProvider, mapProps, mapReadPretty } from '@silver-formily/react'
import { Input as AntdInput, Form } from 'antd'

setValidateLanguage('en')

const FormItem = connect(
  Form.Item,
  mapProps(
    {
      title: 'label',
      description: 'extra',
      required: true,
      validateStatus: true,
    },
    (props, field) => ({
      ...props,
      help: !isVoidField(field) && field.selfErrors.length
        ? field.selfErrors.join(', ')
        : undefined,
    }),
  ),
)

// 大多数第三方组件不支持阅读态，用 mapReadPretty 映射一个阅读态组件即可
function ReadPrettyInput(props: { value?: string }) {
  return <div>{props.value}</div>
}

const Input = connect(
  AntdInput,
  mapReadPretty(ReadPrettyInput),
)

const form = createForm({ validateFirst: true, readPretty: true })

export default function Demo() {
  return (
    <FormProvider form={form}>
      <Form layout="vertical">
        <Field
          name="name"
          title="Name"
          required
          initialValue="Hello world"
          decorator={[FormItem]}
          component={[Input, { placeholder: 'Please Input' }]}
        />
      </Form>
    </FormProvider>
  )
}

// apps/vue-docs/demos/api/shared/map-read-pretty.vue
<script setup lang="ts">
import type { Field as FieldType } from '@silver-formily/core'
import { createForm, setValidateLanguage } from '@silver-formily/core'
import {
  connect,
  Field,
  FormProvider,
  mapProps,
  mapReadPretty,
} from '@silver-formily/vue'
import { ElForm, ElFormItem, ElInput } from 'element-plus'
import { defineComponent, h } from 'vue'

setValidateLanguage('en')

const FormItem = connect(
  ElFormItem,
  mapProps(
    {
      title: 'label',
      description: 'extra',
      required: true,
      validateStatus: true,
    },
    (props, field: FieldType) => ({
      ...props,
      help: field.selfErrors?.length ? field.selfErrors : undefined,
    }),
  ),
)

const ReadPrettyInput = defineComponent({
  name: 'ReadPrettyInput',
  setup(_props, { attrs }) {
    return () => h('div', {}, [attrs.modelValue as any])
  },
})

const Input = connect(
  ElInput,
  mapReadPretty(ReadPrettyInput),
)

const form = createForm({ validateFirst: true, readPretty: true })
</script>

<template>
  <FormProvider :form="form">
    <ElForm layout="vertical">
      <Field
        name="name"
        title="Name"
        required
        initial-value="Hello world"
        :decorator="[FormItem]"
        :component="[Input, { placeholder: 'Please ElInput' }]"
      />
    </ElForm>
  </FormProvider>
</template>
