// apps/react-docs/demos/api/shared/observer.tsx
import { createForm } from '@silver-formily/core'
import { Field, FormProvider, observer, useForm } from '@silver-formily/react'
import { Input, Space } from 'antd'

// 读取响应式模型（Form/Field 等）的自定义组件必须用 observer 包裹，
// 依赖变化时只有当前组件重渲染
const FormPreviewer = observer(() => {
  const form = useForm()
  return (
    <div>
      {JSON.stringify(form.values)}
    </div>
  )
})

const form = createForm({ validateFirst: true })

export default function Demo() {
  return (
    <FormProvider form={form}>
      <Space>
        <Field
          name="name"
          title="Name"
          required
          component={[Input, { placeholder: 'Please Input' }]}
        />
        <FormPreviewer />
      </Space>
    </FormProvider>
  )
}

// apps/vue-docs/demos/api/shared/observer.vue
<script setup lang="tsx">
import { createForm } from '@silver-formily/core'
import { observer } from '@silver-formily/reactive-vue'
import { Field, FormProvider, useForm } from '@silver-formily/vue'
import { ElInput, ElSpace } from 'element-plus'
import { defineComponent } from 'vue'

const FormPreviewer = observer(
  defineComponent({
    name: 'FormPreviewer',
    setup() {
      const formRef = useForm()
      return () => <div>{JSON.stringify(formRef.value?.values)}</div>
    },
  }),
)

const form = createForm({ validateFirst: true })
</script>

<template>
  <FormProvider :form="form">
    <ElSpace>
      <Field
        name="name"
        title="Name"
        required
        :component="[ElInput, { placeholder: 'Please ElInput' }]"
      />
      <FormPreviewer />
    </ElSpace>
  </FormProvider>
</template>
