// apps/react-docs/demos/api/components/schema-field-with-schema.tsx
import { createForm } from '@silver-formily/core'
import { createSchemaField, FormProvider } from '@silver-formily/react'
import { Input } from 'antd'

const form = createForm()

const SchemaField = createSchemaField({
  components: {
    Input,
  },
})

const schema = {
  type: 'object',
  properties: {
    input: {
      'type': 'string',
      'x-component': 'Input',
    },
  },
}

export default function Demo() {
  return (
    <FormProvider form={form}>
      {/* 直接传入 JSON Schema 对象渲染 */}
      <SchemaField schema={schema} />
    </FormProvider>
  )
}

// apps/vue-docs/demos/api/components/schema-field-with-schema.vue
<script>
import { createForm } from '@silver-formily/core'
import { createSchemaField, FormProvider } from '@silver-formily/vue'
import { ElInput } from 'element-plus'

const { SchemaField } = createSchemaField({
  components: {
    ElInput,
  },
})

export default {
  components: { FormProvider, SchemaField },
  data() {
    return {
      form: createForm(),
    }
  },
}
</script>

<template>
  <FormProvider :form="form">
    <SchemaField
      :schema="{
        type: 'object',
        properties: {
          input: {
            'type': 'string',
            'x-component': 'ElInput',
          },
        },
      }"
    />
  </FormProvider>
</template>
