// apps/reactive-vue-docs/demos/autorunEffect.vue
<script setup lang="ts">
import { observable } from '@silver-formily/reactive'
import { autorunEffect } from '@silver-formily/reactive-vue'
import { ref } from 'vue'

const state = observable({
  count: 0,
})

const writtenCount = ref(0)
const trackedCount = ref(0)
const runCount = ref(0)
const active = ref(true)

const stop = autorunEffect(() => {
  runCount.value += 1
  trackedCount.value = state.count
})

function syncWrittenCount() {
  writtenCount.value = state.count
}

function increment() {
  state.count += 1
  syncWrittenCount()
}

function addTen() {
  state.count += 10
  syncWrittenCount()
}

function dispose() {
  if (!active.value)
    return
  stop()
  active.value = false
}
</script>

<template>
  <div>
    <div class="demoToolbar">
      <button class="demoButton" @click="increment">
        count + 1
      </button>
      <button class="demoButton" @click="addTen">
        count + 10
      </button>
      <button class="demoButton secondary" :disabled="!active" @click="dispose">
        dispose
      </button>
    </div>

    <div>手动写入值：{{ writtenCount }}</div>
    <div>autorun 同步值：{{ trackedCount }}</div>
    <div>autorun 执行次数：{{ runCount }}</div>
    <div>订阅状态：{{ active ? 'active' : 'disposed' }}</div>
  </div>
</template>

<style scoped src="./effectDemo.css"></style>

// apps/reactive-react-docs/demos/autorunEffect.tsx
import { observable } from '@silver-formily/reactive'
import { autorunEffect } from '@silver-formily/reactive-react'
import { useState } from 'react'
import './demoStyles.css'

const obs = observable({ count: 0 })

function AutoRunner({ onLog }: { onLog: (message: string) => void }) {
  // 组件提交后自动运行，count 变化时重跑，组件卸载时自动销毁
  autorunEffect(() => {
    onLog(`autorun 执行，当前 count = ${obs.count}`)
  })

  return <div className="demoText">autorunEffect 挂载中</div>
}

export default function AutorunEffectDemo() {
  const [active, setActive] = useState(true)
  const [logs, setLogs] = useState<string[]>([])

  const log = (message: string) => {
    setLogs(prev => [...prev, message])
  }

  return (
    <div>
      <div className="demoToolbar">
        <button
          className="demoButton"
          onClick={() => {
            obs.count++
          }}
        >
          count +1
        </button>
        <button
          className="demoButton"
          onClick={() => {
            setActive(value => !value)
          }}
        >
          {active ? '卸载子组件' : '重新挂载子组件'}
        </button>
      </div>
      <div className="demoText">
        当前 count：
        {obs.count}
      </div>
      {active && <AutoRunner onLog={log} />}
      <div>
        {logs.slice(-5).map((log, index) => (
          <div key={index} className="demoText secondary">{log}</div>
        ))}
      </div>
    </div>
  )
}
