// apps/reactive-vue-docs/demos/useObserver.vue
<script setup lang="ts">
import { observable } from '@silver-formily/reactive'
import { useObserver } from '@silver-formily/reactive-vue'

useObserver()

const obs = observable({
  value: 'Hello world',
})

function handleInput(event: Event) {
  const target = event.target as HTMLInputElement | null
  if (target) {
    obs.value = target.value
  }
}
</script>

<template>
  <div>
    <div>
      <input
        :style="{
          height: 28,
          padding: '0 8px',
          border: '2px solid #888',
          borderRadius: 3,
        }"
        :value="obs.value"
        @input="handleInput"
      >
    </div>
    <div>{{ obs.value }}</div>
  </div>
</template>

// apps/reactive-react-docs/demos/useObserver.tsx
import { observable } from '@silver-formily/reactive'
import { useObserver } from '@silver-formily/reactive-react'
import './demoStyles.css'

const obs = observable({
  value: 'Hello world',
})

// useObserver 是 observer 的内部实现，直接在组件内追踪 view 函数的依赖
function ObservedInput() {
  return useObserver(() => {
    return (
      <div>
        <input
          className="demoInput"
          value={obs.value}
          onChange={(event) => {
            obs.value = event.target.value
          }}
        />
        <div className="demoText">{obs.value}</div>
      </div>
    )
  })
}

export default ObservedInput
